### ISSUE TITLE
Bold/Italic incorrect

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC#42]
![IRC](http://i.imgur.com/jRUh1EM.png)
![OIRC](http://i.imgur.com/eyySSYj.png)

Looks like OIRC is interpreting control characters incorrectly.

**Comment by Sorunome** [comment]
I do it the way hexchat laid it out, \x1D is italic and \x16 is invert.

**Comment by Eeems** [comment]
Looks like \x16 is handled differently between clients. It might be prudent to just handle it as italics

**Comment by Sorunome** [comment]
Your client doesn't follow the standard.
http://en.wikichip.org/wiki/irc/colors

**Comment by Eeems** [comment]
Colloquy handles \x16 as italics and \x1D does nothing
IRCCloud handles \x16 and \x1D as italics
Chatzilla doesn't handle \x16 as anything

There is no proper standard for any of this. Clients just loosely follow what mIRC did. I think \x16 being treated as inverse doesn't properly represent things and some more research is required before just labelling this as a wontfix.

**Comment by Sorunome** [comment]
Hexchat handles \x1D as italic, \x16 as reverse.
xChat handles \x16 as reverse and no italic
irssi handles the same as xchat
kiwiirc handles \x1D as italic and doesn't handle \x16
mibbit handles neither
pidgin handles neither

**Comment by Eeems** [comment]
So from what I can tell, it might be best to handle both as italic.

**Comment by ailin-nemui** [comment]
There might be some confusion due to terminal configuration mistakes as well. Irssi handles `\x1d` as italics and `\x16` as reverse if your terminal is configured correctly. See https://github.com/irssi/irssi/blob/master/src/fe-common/core/formats.c#L1373 and http://www.visualirc.net/tech-attrs.php (only "ASCII value" is relevant protocol information on that page, the other columns are visual-irc specific implementation details) As far as I know, this implementation matches mIRC's

**Comment by Eeems** [comment]
@ailin-nemui Thanks for that. I'm of the impression currently that \x1d is the correct one for italics, but there are a couple IRC Clients that don't quite do what they should. I've had [send with style to update to \x1D](https://github.com/dogancelik/irccloud-sws/issues/5) so people using that format on IRCCloud will use the correct symbol. I can talk to IRCCloud and see why they are supporting both (Probably for the same reason I think OIRC should).

I can probably also pursue why Colloquy handles it different.

**Comment by Eeems** [comment]
Got a response as to why \x16 is interpreted as italics. It looks like we might want to track down clients that are still handling it as italics and get them to move to \x1d
![Chat lot](https://dl.dropboxusercontent.com/u/763272/img/screenshot.32.png)

**Comment by Sorunome** [comment]
close?

**Comment by Sorunome** [comment]
inactive / oirc interprets the spec correctly
