### ISSUE TITLE
Admin Interface. Completely remove channels.

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC#47]
Looks like there is no way to completely remove a channel with the admin interface.
You can also remove all entries for a channel and then save. When you try to reload it you can't see the channel lists again (TypeError: chan.networks[0] is undefined).

**Comment by Sorunome** [comment]
The thing is that the ID corresponding to the channels in the database is in the ordered list of the config, meaning that removing a channel would result in wrong data. That is why I decided to only allow disabling. Same with networks.

**Comment by Eeems** [comment]
Don't remove the bug label. Still got that nasty not rendering when the last entry ;)

**Comment by Eeems** [comment]
Code in question causing the issue: https://github.com/Sorunome/OmnomIRC2/blob/f5e98fd7652929b66fea4e28ba649e06dc79a137/omnomirc_www/admin.js#L248

**Comment by Sorunome** [comment]
That was it indeed, fixed in https://github.com/Sorunome/OmnomIRC2/commit/9c3a8480671afee974cab7148aa1d043a87be1dc

**Comment by Sorunome** [comment]
Bug fixed with https://github.com/Sorunome/OmnomIRC2/commit/c77b7fd82b83ce899982db498d470f4825ac1d9a

**Comment by Sorunome** [comment]
Wait, so why is this still open? The bug is fixed? Or was there an enhancement-request somewhere in here I missed?
Because I said I didn't want to allow completely removing a channel, due to ID stuff.

**Comment by Eeems** [comment]
What ID things are you talking about? I'd assume removing a channel would also handle deletion of any related data.

**Comment by Sorunome** [comment]
hm, ok, that could work, then, i'd add a warning then, though, that it deletes all related data to that channel.

**Comment by Eeems** [comment]
I'd be okay with that. Have a confirm dialog with the warning or something similar.

**Comment by Sorunome** [comment]
Done with https://github.com/Sorunome/OmnomIRC/commit/50c85820d28abfb53423450813f68ef46fe96f41
