### ISSUE TITLE
Pooling websockets

### ISSUE THREAD

**Issue by Sorunome** [Sorunome/OmnomIRC#54]
So that there is only one open websocket connection.

Also this will probably help: https://github.com/Eeems/PooledWebSocket

**Comment by Eeems** [comment]
https://www.npmjs.com/package/pooledwebsocket
Use package.json and npm to pull from pooledwebsocket if you do go down that route and don't roll your own. I'll get some documentation written up eventually.

**Comment by Sorunome** [comment]
Added in https://github.com/Sorunome/OmnomIRC/commit/445d0e00668d3e21667e5ae82a2fbcbcc972e165

**Comment by Eeems** [comment]
Oh really? How's it handle?
Anything missing from the exposed API?

**Comment by Sorunome** [comment]
I had to do the changes of the pull request over there, I minified the source and the fallback isn't working yet, due to the issue I opened over there.
