### ISSUE TITLE
Don't notify on unapproved topics

### ISSUE THREAD

**Issue by Eeems** [Sorunome/OmnomIRC#58]
OIRC shouldn't notify on unapproved topics. It should instead only notify on them when they've been approved.

**Comment by Sorunome** [comment]
[*] SMF
[ ] phpBB
[ ] abxd

**Comment by Sorunome** [comment]
smf: https://github.com/Sorunome/OmnomIRC/commit/52a5e858d9b0857b294a5390e79475e9c023d44b
phpbb: https://github.com/Sorunome/OmnomIRC/commit/8ac3305db12aa4904f7b19cb9cf9a89fd0b5a62a
abxd: feature doesn't exist as far as i can tell
