### ISSUE TITLE
Disable Memcache with Option

### ISSUE THREAD

**Issue by theonlypwner** [Sorunome/OmnomIRC#65]
```
Notice: Memcache::connect(): Server localhost (tcp 11211, udp 0) failed with: Network is unreachable (101) in [.../]/php/omnomirc.php on line 127

Warning: Memcache::connect(): Can't connect to localhost:11211, Network is unreachable (101) in [.../]php/omnomirc.php on line 127
```

Adding an option to disable memcache would fix this issue.

**Comment by Sorunome** [comment]
why would you even have the memcache library installed while actually not having the server installed, heehee. I'll fix it anyways ;)

**Comment by theonlypwner** [comment]
When your hosting environment is set up for you, memcache might be installed with PHP, even if the server isn't running.

**Comment by Eeems** [comment]
I would expect them not to have it turned on though.

**Comment by theonlypwner** [comment]
I don't see how it's unreasonable to have the memcache library installed but no memcache server running.

**Comment by Eeems** [comment]
Do they offer memcache as a service?

**Comment by theonlypwner** [comment]
By default, their PHP installation has the memcache library pre-installed. You can set up a memcached server manually if you want, but if you don't, OmnomIRC should not malfunction as reported in this issue.

**Comment by Eeems** [comment]
It may be installed by default, the confusion I'm having is that it's enabled by default when the host doesn't have it.
I totally agree that instead of just feature detecting, OIRC should also have a setting to enable/disable features.

**Comment by Sorunome** [comment]
how about detection if it is running instead?

**Comment by Eeems** [comment]
That might be a little too expensive to do each hit

**Comment by Sorunome** [comment]
Hm, fair enough. I guess I'll do auto-detection on installation then
