### ISSUE TITLE
Chrome attempts to autofill the input box.

### ISSUE THREAD

**Issue by c4ooo** [Sorunome/OmnomIRC#69]
The values it attempts to auto fill are "I sortof need the normal cause that's what my 3d collision code uses" which  is a message i sent into OIRC, and "Progress on tile mapper." the title of a thread i created on codewalrus(?)(!!). There are no more sentences it attempts to autofill.
![image](https://cloud.githubusercontent.com/assets/8150103/17172051/608fc2be-53c1-11e6-94f9-08a6561a82df.png)

**Comment by c4ooo** [comment]
Also, when i my curser is inside the inputbox, and i click inside the box again, this pops up: 
![image](https://cloud.githubusercontent.com/assets/8150103/17172338/9e1485d8-53c2-11e6-9170-28f6a7829cee.png)

**Comment by Sorunome** [comment]
can't reproduce, perhaps i fixed it "by accident" and don't remember
