### ISSUE TITLE
`async` is reserved keyword as of Python 3.7

### ISSUE THREAD

**Issue by theonlypwner** [Sorunome/OmnomIRC#73]
I get errors when running the bot, since `async` is a reserved keyword.

```console
$ ./omnomirc.sh
  File "bot.py", line 453
    @oirc.async
          ^
SyntaxError: invalid syntax
```

Renaming `async` to `async2` in `bot/oirc_include.py` and `bot/bot.py` temporarily fixes the issue.

**Comment by Sorunome** [comment]
heya, thank you for all your issues and PRs! Unfortunately soru isn't really supporting this anymore, so if you want to PR a fix for this she can look at it and merge it. Thank you for your enthusiasm, though!

**Comment by theonlypwner** [comment]
I'll continue to submit pull requests for stuff I fix, and I'll post issues for bugs I noticed but haven't fixed yet.
